# Generated by Django 2.2.6 on 2019-11-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField(verbose_name='Name of the book')),
                ('book_text', models.TextField(verbose_name='Text of the book')),
                ('pub_date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField(verbose_name='Name of author')),
                ('comment_text', models.TextField(verbose_name='Text of comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
