# Generated by Django 3.0 on 2019-12-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='NULL', upload_to='archive/'),
        ),
    ]
