# Generated by Django 3.0 on 2019-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191213_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='NULL', upload_to='archive'),
        ),
    ]
